### ISSUE TITLE
@/src/components/Editor.vue: 本文が空の場合保存ができないようにしてほしい

### ISSUE THREAD

**Issue by ghost** [suzuri-note/suzuri#11]
掲題の通り。
現状、本文が空でも保存ボタンをクリックすることができる。services側では本文が空（正確にはbodyがfalseになる場合）にエラーを吐くように設定している。
本文が空のデータが保存されるのは想定する動作ではないと考えるため、UI側でも空の場合はボタンをdisabledにするなど対応をお願いしたい。

https://github.com/suzuri-note/suzuri/blob/b4b69920b14ffe312769f1f80f439403796f1b06/src/components/Editor.vue#L16-L20

**Comment by kecbigmt** [comment]
#15 の d3fcb68 で実装
