### ISSUE TITLE
@/services/note: list()でエラーが返ってくる

### ISSUE THREAD

**Issue by kecbigmt** [suzuri-note/suzuri#5]
@bsk00wisteria 
対応お願いしますー
![image](https://user-images.githubusercontent.com/26671794/57154044-d7c52900-6e12-11e9-94c6-e2457b743a12.png)

App.vue 42-52行目のあたりでlist()を使用
https://github.com/suzuri-note/suzuri/blob/536cfc1a03fe4414569697f8f32349c2e69192e4/src/App.vue#L42-L52

**Comment by ghost** [comment]
## 原因
JSON.parseがうまく行かないことによるエラー
localStorageに能動的に保存したのではない別のデータが紛れ込んでいる場合に発生

## 詳細
今回であれば、下記が（おそらくVueによって）登録されていた
```
loglevel:webpack: SILENT
```
SILENTはただの文字列で、JSON形式ではないためエラーが発生した。

## 解決方法
以下対応を行う。
1. note.save(): 現在出力しているUUID（shortid）にprefix `SuzuriMemoId.`を追加
2. note.list(): localStorageからデータを引っ張ってくる際、prefixで検索をかける

## 補足
なお他に定義されている下記関数に関しては、呼び出し元に渡されたIDによって動作を行うため同問題は発生し得ない
* get
* delete

**Comment by ghost** [comment]
@kecbigmt 
feature/storeブランチよりfixブランチを切って対応を行う。
完了後、PRをfeature/storeに対して行う。
